# Generated by Django 6.0.5 on 2026-05-23 14:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Участник процесса',
                'verbose_name_plural': 'Участники процесса',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название киностудии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Киностудия',
                'verbose_name_plural': 'Киностудии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FilmMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('trailer', 'Трейлер'), ('teaser', 'Тизер'), ('full_movie', 'Полный фильм'), ('poster', 'Постер'), ('still', 'Кадр из фильма')], default='trailer', max_length=50, verbose_name='Тип медиа')),
                ('file', models.FileField(blank=True, null=True, upload_to='film_media/', verbose_name='Файл')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='movies.film', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Медиафайл фильма',
                'verbose_name_plural': 'Медиафайлы фильмов',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='acted_films', to='movies.person', verbose_name='Актеры'),
        ),
        migrations.AddField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='directed_films', to='movies.person', verbose_name='Режиссеры'),
        ),
        migrations.AddField(
            model_name='film',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='produced_films', to='movies.person', verbose_name='Продюсеры'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст рецензии')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецензии')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.film', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Рецензия',
                'verbose_name_plural': 'Рецензии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='film',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films', to='movies.studio', verbose_name='Киностудия'),
        ),
    ]
